/* Generated by Cython 0.29.21 */

#ifndef __PYX_HAVE__shrdr___shrdr
#define __PYX_HAVE__shrdr___shrdr

#include "Python.h"
struct PyObject_QpboInt;
struct PyObject_ParallelQpboInt;

/* "shrdr/src/_shrdr.pyx":13
 * ctypedef uint32_t NodeIdxInt
 * 
 * cdef public class QpboInt[object PyObject_QpboInt, type QpboInt]:             # <<<<<<<<<<<<<<
 *     cdef Qpbo[CapInt, ArcIdxInt, NodeIdxInt]* c_qpbo
 * 
 */
struct PyObject_QpboInt {
  PyObject_HEAD
  mbk::Qpbo<__pyx_t_5shrdr_6_shrdr_CapInt,__pyx_t_5shrdr_6_shrdr_ArcIdxInt,__pyx_t_5shrdr_6_shrdr_NodeIdxInt>  *c_qpbo;
};

/* "shrdr/src/_shrdr.pyx":68
 *         self.c_qpbo.compute_weak_persistencies()
 * 
 * cdef public class ParallelQpboInt[object PyObject_ParallelQpboInt, type ParallelQpboInt]:             # <<<<<<<<<<<<<<
 *     cdef ParallelQpbo[CapInt, ArcIdxInt, NodeIdxInt]* c_pqpbo
 * 
 */
struct PyObject_ParallelQpboInt {
  PyObject_HEAD
  mbk::ParallelQpbo<__pyx_t_5shrdr_6_shrdr_CapInt,__pyx_t_5shrdr_6_shrdr_ArcIdxInt,__pyx_t_5shrdr_6_shrdr_NodeIdxInt>  *c_pqpbo;
};

#ifndef __PYX_HAVE_API__shrdr___shrdr

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(PyTypeObject) QpboInt;
__PYX_EXTERN_C DL_IMPORT(PyTypeObject) ParallelQpboInt;

#endif /* !__PYX_HAVE_API__shrdr___shrdr */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC init_shrdr(void);
#else
PyMODINIT_FUNC PyInit__shrdr(void);
#endif

#endif /* !__PYX_HAVE__shrdr___shrdr */
